### PR TITLE
fix github link on packagedown site & address deprecations

### LINKED ISSUE #207: Github link on website doesn't direct to github repo
I noticed the Github logo link on the [main site](https://shannonpileggi.github.io/gtreg/) directs back to the main site instead of redirecting to [github repo](https://github.com/shannonpileggi/gtreg). 

Thanks for making this great package!

### LINKED ISSUE #210: Warning message with tbl_ae() - deprecated function
``` r
library(gtreg)

df_adverse_events |>
  tbl_ae(id = patient_id, ae = adverse_event, soc = system_organ_class, by = grade)
#> Warning: `fct_explicit_na()` was deprecated in forcats 1.0.0.
#> ℹ Please use `fct_na_value_to_level()` instead.
#> ℹ The deprecated feature was likely used in the gtreg package.
#>   Please report the issue at <https://github.com/shannonpileggi/gtreg/issues>.
#> This warning is displayed once every 8 hours.
#> Call `lifecycle::last_lifecycle_warnings()` to see where this warning was
#> generated.
```

<sup>Created on 2023-05-15 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

### PR DESCRIPTION
**Pull request by shannonpileggi**
**What changes are proposed in this pull request?**

Fix GitHub link on pkgdown site.

Address deprecated `purrr::when()` and `forcats::fct_explicit_na()`.

Update package versions for dependencies.

**If there is an GitHub issue associated with this pull request, please provide link.**

closes #207 
closes #210 

--------------------------------------------------------------------------------

Checklist for PR reviewer

- [ ] Ensure all package dependencies are installed by running `renv::install()`
- [ ] PR branch has pulled the most recent updates from main branch. Ensure the pull request branch and your local version match and both have the latest updates from the main branch.
- [ ] If a new function was added, function included in `_pkgdown.yml`
- [ ] If a bug was fixed, a unit test was added for the bug check
- [ ] Run `pkgdown::build_site()`. Check the R console for errors, and review the rendered website.
- [ ] Code coverage is suitable for any new functions/features. Review coverage with `covr::report()`. Before you run, set `Sys.setenv(NOT_CRAN="true")` and begin in a fresh R session without any packages loaded. 
- [ ] R CMD Check runs without errors, warnings, and notes
- [ ] `usethis::use_spell_check()` runs with no spelling errors in documentation
- [ ] Has `NEWS.md` been updated with the changes from this pull request under the heading "`# gtreg (development version)`". If there is an issue associated with the pull request, reference it in parentheses at the end update (see `NEWS.md` for examples).
- [ ] Has the version number been incremented using `usethis::use_version(which = "dev")` 
- [ ] Approve Pull Request
- [ ] Merge the PR. Please use "Squash and merge".

### CODE REVIEW

**Comment by ddsjoberg** [comment]
this edit looks good. I would recommend addressing the deprecation warnings before merging any PRs (I mean, not a big deal for this small change, but generally, would prefer to merge PRs when there are no errors/warnings in the checks).

**Review by ddsjoberg — APPROVED** [review]
✔️

**Comment by shannonpileggi** [comment]
note to self this is still breaking on `.construct_summary_table` - SOC counts seem to be off with new forcats update

**Comment by shannonpileggi** [comment]
@ddsjoberg does this note matter for CRAN submissions?

❯ checking dependencies in R code ... NOTE
  Unexported object imported by a ':::' call: 'forcats:::check_factor'
    See the note in ?`:::` about the use of this operator.

0 errors ✔ | 0 warnings ✔ | 1 note ✖

**Comment by ddsjoberg** [comment]
CRAN won't accept with that note, unfortunately

**Comment by shannonpileggi** [comment]
Ok I looked up solutions and found this thread [Build a package import a non-exported function from a imported package](https://community.rstudio.com/t/build-a-package-import-a-non-exported-function-from-a-imported-package/18062/2). As `forcats` has MIT license I think ok to copy/paste function here.

**Comment by shannonpileggi** [comment]
ok @ddsjoberg ready for review / help 🙏 

`devtools::check()` looks good 👌 
but
`pkgdown::build_site()` has an error 🤔

**Comment by ddsjoberg** [comment]
@shannonpileggi looks great!

what was your error on `pkgdown::build_site()`? It ran without issue on my machine.

**Comment by shannonpileggi** [comment]
wellllll here is there error i get with devmode on, but when i turn devmode off it runs fine 🙃 

image

image
image
image

**Pull request merged**
