### PR TITLE
Create `rd_documentation_images.R`

### LINKED ISSUE #27: Update help files to include an image of the saved gt table.
- [ ] Build a bare-bones pkg to run all examples in a pkg, and if the examples contain a gtsummary/gt table save the table as an image
     - In gtsummary, the function only saves objects that end in `*_ex` or `*_ex1` or `*_ex2`, etc. Should this be a requirement, or simply save all table images?
     - Put the pkg on R Universe (not going to CRAN)
 - [ ] Add a script to gtreg that will use the pkg above to save the images
 - [ ] Update function help files to display the images.

### PR DESCRIPTION
**Pull request by ddsjoberg**
Hello @shannonpileggi !

I have added a file that will create images of all gt/gtsummary tables created in the example section of the help files.

closes #27

- [ ] Add examples to each of the function help files
- [ ] Run the `rd_documentation_images.R` script to save the images
- [ ] Update the documentation files to include the images (see `@section Example Output:` example in `add_overall.R`)
- [ ] Futz with the `width=` argument until rendered help files look good

### CODE REVIEW

**Comment by shannonpileggi** [comment]
This looks pretty sweet!  But I'm having a bit of trouble getting it up and running.

I restarted R, and then I got this:

```
> gt.doc.images::save_help_file_images(pkg = "gtreg")
√ Working on add_overall.tbl_adverse_event
Error in find.package(package, lib.loc, verbose = verbose) : 
  there is no package called ‘gtreg’
```

So should I be loading `gtreg`, contrary to comment 3?

**Comment by shannonpileggi** [comment]
This is vv cool! 

Where should I see the images rendered? They won't render in the standard help file like `?add_overall`, correct? So is this meant for display on the pkgdown site or the readme?

Should I be updating the readme with these images, or should the readme stay as is?

**Comment by ddsjoberg** [comment]
> Where should I see the images rendered? They won't render in the standard help file like `?add_overall`, correct? So is this meant for display on the pkgdown site or the readme?

The images will render both in the help files and on the pkgdown site. There are a few nuances, however. The images will not render in the help file is you've loaded the package using `devtools::load_all()`. You need to re-document, install the package, then inspect the help file.

> Should I be updating the readme with these images, or should the readme stay as is?

The README includes the option below and the figures will be saved automatically. So we don't need to worry about the README here.

```r
knitr::opts_chunk$set(
  fig.path = "man/figures/README-",
)
```

**Comment by shannonpileggi** [comment]
Pushed some images, will come back later to check regex stuff and update documentation!

**Comment by shannonpileggi** [comment]
1. Does the order of commands matter at all in the roxygen section?  Does `@export` need to come after the example output section?
2. What does the `NULL` line do in the roxygen of `add_overall.R`?

**Comment by ddsjoberg** [comment]
> 1. Does the order of commands matter at all in the roxygen section?  Does `@export` need to come after the example output section?

I don't think so. The Rd files seems to have a set order to them, and where ever the sections appear in roxygen2 comments, the ordering seems to be the same in the rendered file.

> 2. What does the `NULL` line do in the roxygen of `add_overall.R`?

That creates the base of the help file, and each method is then added to it. There are various ways to document multiple files in a single Rd file...this is just the one I can remember.

**Comment by shannonpileggi** [comment]
> > 2. What does the `NULL` line do in the roxygen of `add_overall.R`?
> 
> That creates the base of the help file, and each method is then added to it. There are various ways to document multiple files in a single Rd file...this is just the one I can remember.

So when you say method, is that related to `@rdname`?  I might need to chat few a couple of things here when we get the chance.

**Comment by ddsjoberg** [comment]
> > > 2. What does the `NULL` line do in the roxygen of `add_overall.R`?
> > 
> > 
> > That creates the base of the help file, and each method is then added to it. There are various ways to document multiple files in a single Rd file...this is just the one I can remember.
> 
> So when you say method, is that related to `@rdname`? I might need to chat few a couple of things here when we get the chance.

I mean each S3 method, `add_overall.tbl_ae()`, `add_overall.tbl_ae_count()`, and `add_overall.tbl_ae_focus()`.

We can chat anytime!

**Comment by shannonpileggi** [comment]
I amended `tbl_ae_count.R`, but I think I am still missing a couple of things - my .Rd deleted, and this is the note I get:

image

**Comment by ddsjoberg** [comment]
Hmmm, that is strange. Typically roxygen2 can infer the title and description fields. But if it's having trouble, you can add:

```
#' @title Tabulate Raw AE Counts
#'
#' @description Create a table with the number of AE that were reported.
#'
#' @inheritParams tbl_ae
```

**Comment by shannonpileggi** [comment]
k i followed the images steps, and things are executing without error, but from what i can tell no images are being created from the two examples in `tbl_ae()` and i can't quite tell why.  have any idea what is going on here?

i tried squinting at the roxygen stuff to make sure it was all the same, and i also tried inspecting a bit of source code for `gt.doc.images`  but i'm struggling to figure it out. and i'm pretty sure it is going to be something super obvious.

image

**Comment by ddsjoberg** [comment]
@shannonpileggi I just tried on my machine, and it saved the images from `tbl_ae()`. My guess is that you need to re-document the help files (`devtools::document()`), re-install the gtreg package, then create the images. Do you know if you have re-documented?

**Comment by shannonpileggi** [comment]
omg yes that was it i knew it was prob something obvi 🤦 sorry!

**Comment by shannonpileggi** [comment]
sorry to make this one so drawn out!  i think it is ready now @ddsjoberg

**Comment by shannonpileggi** [comment]
images have been resized in the documentation files - hopefully they look ok now!  let me know if they need further adjustments.

also, `add_overall_ex1.png` has been cut off at the edge - is this a limitation of the image capture procedures?

image

**Comment by ddsjoberg** [comment]
I am not sure why it was cut off. I just made a screenshot and added manually

**Pull request merged**
