### PR TITLE
adding `.linebreak_gtsummary()` function

### LINKED ISSUE #79: Add function to construct `linebreak()` call
A function like the one below could be added to the kableExtra calls like this `gtsummary::as_kable_extra(col.names = .gts_kable_extra_linebreak_call(x))`.

The function uses the tables' defined labels and the assigned column alignment to create the call.

```r
.gts_kable_extra_linebreak_call <- function(x,
                                            align = NULL, 
                                            double_escape = FALSE, 
                                            linebreaker = "\n") {
  # check kableExtra installation? (or add it to Imports:)
  
  # set align arg
  align <- align %||%
    stringr::str_sub(dplyr::filter(x$table_styling$header, !hide)$align, 1, 1)
  
  # return linebreak result
  kableExtra::linebreak(
    x = dplyr::filter(x$table_styling$header, !hide)$label,
    align = align,
    double_escape = double_escape, 
    linebreaker = linebreaker
  )
}
```

### PR DESCRIPTION
**Pull request by ddsjoberg**
**What changes are proposed in this pull request?**

adding `.linebreak_gtsummary()` function that uses the information in the gtsummary object to set alignment. The function also takes the defined column headers, and converts the markdown bold syntax (double stars only) to LaTeX code.

**If there is an GitHub issue associated with this pull request, please provide link.**
closes #79 

This is not quite ready for full review and merging. We should have a conversation about the functionality that will be useful (only converts markdown double stars at the moment).

--------------------------------------------------------------------------------

Checklist for PR reviewer

- [ ] Ensure all package dependencies are installed by running `renv::install()`
- [ ] PR branch has pulled the most recent updates from main branch. Ensure the pull request branch and your local version match and both have the latest updates from the main branch.
- [ ] If a new function was added, function included in `_pkgdown.yml`
- [ ] If a bug was fixed, a unit test was added for the bug check
- [ ] Run `pkgdown::build_site()`. Check the R console for errors, and review the rendered website.
- [ ] Code coverage is suitable for any new functions/features. Review coverage with `covr::report()`. Before you run, set `Sys.setenv(NOT_CRAN="true")` and begin in a fresh R session without any packages loaded. 
- [ ] R CMD Check runs without errors, warnings, and notes
- [ ] `usethis::use_spell_check()` runs with no spelling errors in documentation
- [ ] Has `NEWS.md` been updated with the changes from this pull request under the heading "`# gtreg (development version)`". If there is an issue associated with the pull request, reference it in parentheses at the end update (see `NEWS.md` for examples).
- [ ] Has the version number been incremented using `usethis::use_version(which = "dev")` 
- [ ] Approve Pull Request
- [ ] Merge the PR. Please use "Squash and merge".

### CODE REVIEW

**Comment by ddsjoberg** [comment]
It wasn't so bad to add conversions of `**`, `*`, `__`, and `_`,  and that is in the current version.

One thing that will still need to be figured out, is how to handle the spanning header. The bold/italic code is being stripped and I haven't ever thought about how to handle this before!

``` r
library(gtreg)

tbl <-
  df_adverse_events %>%
  tbl_ae(
    id = patient_id,
    ae = adverse_event,
    by = grade,
    strata = trt,
    header_by = "**Grade {level}**"
  ) %>%
  as_kable_extra(
    col.names = .linebreak_gtsummary(.),
    escape = FALSE,
    format = "latex", 
    return_call = TRUE # return kableExtra calls, not the latex code
  )

tbl$kable
#> knitr::kable(col.names = c("\\textbf{Adverse Event}", "\\textbf{Grade 1}", 
#> "\\textbf{Grade 2}", "\\textbf{Grade 3}", "\\textbf{Grade 4}", 
#> "\\textbf{Grade 5}", "\\textbf{Grade 1}", "\\textbf{Grade 2}", 
#> "\\textbf{Grade 3}", "\\textbf{Grade 4}", "\\textbf{Grade 5}"
#> ), align = c("l", "c", "c", "c", "c", "c", "c", "c", "c", "c", 
#> "c"), escape = FALSE, format = "latex")
tbl$add_header_above
#> kableExtra::add_header_above(header = c(` ` = 1L, `Drug A, N = 3` = 5L, 
#> `Drug B, N = 7` = 5L))
```

<sup>Created on 2022-02-03 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by ddsjoberg** [comment]
Did a little testing...it seems `kableExtra::add_header_above()` recognizes the `\n` linebreak by default

**Comment by ddsjoberg** [comment]
More thoughts....

Instead of a `use_kable_extra_linebreak()` function that must to be followed by `as_kable_extra(escape = FALSE, format = "latex")`, we could just make a function `as_kable_extra_linebreak()` that wraps `linebreak()` AND `as_kable_extra()`, where we set `escape = FALSE` and `format = "latex"`. This could perhaps reduce user error by mis-specifying the `escape=` argument.

**Comment by shannonpileggi** [comment]
Whew a tiny 🤏 bit of progress. 

### Initial table

```
tbl <-
  df_adverse_events %>%
  tbl_ae(
    id = patient_id,
    ae = adverse_event,
    by = grade,
    strata = trt
  ) %>%
  modify_ae_header(all_ae_cols() ~ "**Grade** \n {by}") %>%
  modify_ae_spanning_header(all_ae_cols() ~ "**{strata}** \n N = {n} / {N}")
```

### Header specs

``` r
position <- c(1, 5, 5)
names_1 <- c(" ", "\\\\textbf\\{Drug A\\} \nN = 3 / 10", "\\\\textbf\\{Drug B\\} \nN = 7 / 10")
names_2 <- kableExtra::linebreak(names_1, double_escape = TRUE)
header_2 <- rlang::set_names(position, names_2)
names_2
#> [1] " "                                                         
#> [2] "\\\\makecell[c]{\\\\textbf\\{Drug A\\} \\\\\\\\N = 3 / 10}"
#> [3] "\\\\makecell[r]{\\\\textbf\\{Drug B\\} \\\\\\\\N = 7 / 10}"
```

<sup>Created on 2022-02-15 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>



### Pdf printed table

```
tbl %>% 
  as_kable_extra(
    col.names = .linebreak_gtsummary(.),
    booktabs = TRUE,
    longtable = TRUE,
    escape = FALSE,
    format = "latex",
    strip_md_bold = FALSE
  )  %>% 
  kableExtra::add_header_above(
    header = header_2,
    escape = FALSE
  )
```

yields 

image

### Sources

I grabbed the `names_1` idea from `kableExtra::add_header_above()` https://github.com/haozhu233/kableExtra/blob/a6af5c067c2b4ca8317736f4a3e6c0f7db508fef/R/add_header_above.R#L371

Other hidden functions that I did not yet get successfully to work, but are still possible, include:
- `kableExtra:::escape_latex()`
- `kableExtra:::escape_latex2()`
- `kableExtra:::input_escape()`

### Next steps

I could work to see if this can be simplified, and how it plays with and without escape options.

Once we have this worked out, a possible place to amend this would be in `gtsummary::as_kable_extra` call to `add_header_above`  https://github.com/ddsjoberg/gtsummary/blob/430806761402ad90c5ad52f03515511279590add/R/as_kable_extra.R#L226

**Comment by ddsjoberg** [comment]
This is awesome!

Trying to get the take-aways from these examples, and outline how this would work in a gtsummary update
1. We can use `.linebreak_gtsummary()` to process both the column names and the spanning headers. 
    - However, we should specify center alignment in the spanning headers, while the alignment of the column headers can inherit the alignment from the gtsummary object
    - Using this function _requires_ the specification of `escape = FALSE` and `format = "latex"`
2. All of this can likely be migrated to an argument in `gtsummary::as_kable_extra(use_linebreak =a TRUE)`
    - If user specified  `use_linebreak = TRUE` we would check that they hadn't also specified `escape = FALSE` or `format = "html"`. WE would throw an error in these cases. In the more likely case that they hadn't specified either of these, we would set the defaults for these arguments.
    - If user specifies `use_linebreak = TRUE` we would overrride the argument to be `strip_md_bold = FALSE`
    - We also need to populate the `kableExtra::add_header_row(escape = <>)` argument to match the `knitr::kable(escape = <>)` value.

Other things to consider:
1. The `as_kable_extra(strip_md_bold=)` argument only exists because I didn't know how to convert markdown to latex/html. I think we could probably remove this function entirely, and a functionality for converting the markdown to HTML code.
2. Are there other markdown syntax items we could convert? Strikethrough would be easy enough...


I think this is pretty much ready to start a pull request into gtsummary! wow!

**Comment by ddsjoberg** [comment]
We will not add `use_linebreak=` argument. Rather we will just use `knitr::is_latex_output()` to detect the output type. If latex then, we will apply the linebreak() formatting to the headers and spanning header.

**Comment by ddsjoberg** [comment]
closing in favor of https://github.com/ddsjoberg/gtsummary/pull/1155

**Pull request closed without merging**
