### PR TITLE
add arguments that pass to complete_ae_data

### LINKED ISSUE #22: Add `tbl_adverse_events(by_values=)` argument
Also relax requirement that the inputs must be character

### LINKED ISSUE #23: Add an argument in `tbl_adverse_events()` that allows user to specify how cells with zero count are displayed.

### LINKED ISSUE #29: Add `tbl_adverse_events(id_df=)` argument

### PR DESCRIPTION
**Pull request by shannonpileggi**
closes #29  
closes #22

### CODE REVIEW

**Comment by shannonpileggi** [comment]
I think this will work?  Unclear until I add more tests.

**Comment by ddsjoberg** [comment]
What do you think about adding unit tests as we go? Probably easier than trying to do it all at the end? @shannonpileggi

**Comment by ddsjoberg** [comment]
I don't think this PR address #23

**Review by ddsjoberg — CHANGES_REQUESTED** [review]
- add unit tests assessing that the args are being respected in the function
- remove #23 from the "closes" comment

**Comment by shannonpileggi** [comment]
> What do you think about adding unit tests as we go? Probably easier than trying to do it all at the end? @shannonpileggi

Okkk I'll stop being lazy! 🙈

**Comment by shannonpileggi** [comment]
> I don't think this PR address #23

Ah ok for some reason as I was reading this as the `missing_text` argument - I get it now!

**Comment by shannonpileggi** [comment]
Ok maybe we should go ahead and address both #7 and #26 here?

I started with #26. Perhaps before I get too far I should check in and see if there are any recommendations for how this should be organized/implemented or what tests make this minimally sufficient. The testing file `test-complete_ae_data.R` is already starting to feel a bit unwieldy so open to streamlining suggestions.

**Comment by ddsjoberg** [comment]
In this PR, why don't we just add tests that address #29 and #22? We can do a separate PR to add robust testing for `tbl_adverse_event()` and `.complete_ae_data()`? Either way is good by me! Just as long as the robust unit tests make it in eventually 😆 

The organization is a great question! I don't have a good answer. For me, unit tests are added as more and more features are included, and my "organization" has just been to add them to the bottom of the testing file. 

Generally, I like to add a test that looks for errors,

```r
expect_error(
  tbl <- tbl_adverse_event(...),
  NA
)
``` 

Followed by tests that ensure the results are what we expected.

```r
expect_equal(
   as_tibble(tbl) %>% pull(stat_1),
   c("5 (56)", NA, "6 (45)") 
)
```

Do you have a way you'd like to organize?

**Comment by shannonpileggi** [comment]
Baby tests now and more robust tests later sounds good! 

No, I don't have a vision for organizing. Just let me know if the script starts to drive you crazy and you see room for improvements.

**Comment by shannonpileggi** [comment]
@ddsjoberg are these tests minimally sufficient or should we add more?

**Comment by ddsjoberg** [comment]
@shannonpileggi great! i'll make the review 👍🏼

**Review by ddsjoberg — APPROVED** [review]
🥳

**Pull request merged**
