### PR TITLE
Adding `modify_ae_header()` and friends

### LINKED ISSUE #87: Allow for adding dynamic Ns using `modify_header()` and `modify_spanning_header()`
We could add functionality allowing us to add custom headers with dynamic Ns and percentages.

- we'd need a function like `gtsummary:::.info_tibble()` to calculate the Ns and percentages for the by and stratum levels
- the sticking point will be that the `modify_header()` function is not S3, and therefore, can't handle any custom code for AE tables
    - we could add wrappers `modify_ae_header()` and `modify_ae_spanning_header()`
    - i could make `modify_header(*)` an S3 function in the next gtsummary release, and we could add a `modify_header.tbl_ae()` method.
    - I lean toward the first.

### LINKED ISSUE #89: Revisit the argument order before release
Depending on how some users interact with our functions, changing the order of the arguments can be a breaking change. Many of our arguments have been added iteratively throughout the dev process, and the order could probably be be placed with more intent.

### LINKED ISSUE #92: Return the complete data?
The `tbl_ae*()` functions return the complete data....do you think we should or should not return this?

PROS: If I user wanted to, it's a very clear what is and is not being reported in the tables.
CONS: It's a (potentially very) big dataset that is likely not needed, and taking up space. If we later find that it's too big to pass around, it's difficult to remove a "feature" users may be taking advantage of.

``` r
library(gtreg)

df_adverse_events %>%
  tbl_ae(
    id = patient_id,
    ae = adverse_event,
    soc = system_organ_class,
    by = grade,
    strata = trt,
    header_by = "**Grade {level}**"
  ) %>%
  purrr::pluck("data_complete")
#> # A tibble: 126 x 7
#>    id    strata soc                                  ae     by    ..soc.. ..ae..
#>    <chr> <chr>  <fct>                                <chr>  <fct> <lgl>   <lgl> 
#>  1 ID 1  Drug B Blood and lymphatic system disorders Anaem~ 4     FALSE   TRUE  
#>  2 ID 1  Drug B Blood and lymphatic system disorders Incre~ 4     FALSE   FALSE 
#>  3 ID 1  Drug B Blood and lymphatic system disorders Incre~ 5     TRUE    TRUE  
#>  4 ID 1  Drug B Blood and lymphatic system disorders Iron ~ NOT ~ FALSE   TRUE  
#>  5 ID 1  Drug B Blood and lymphatic system disorders Throm~ 1     FALSE   FALSE 
#>  6 ID 1  Drug B Blood and lymphatic system disorders Throm~ 3     FALSE   TRUE  
#>  7 ID 1  Drug B Gastrointestinal disorders           Diffi~ NOT ~ FALSE   TRUE  
#>  8 ID 1  Drug B Gastrointestinal disorders           Intes~ 1     FALSE   FALSE 
#>  9 ID 1  Drug B Gastrointestinal disorders           Intes~ 2     FALSE   TRUE  
#> 10 ID 1  Drug B Gastrointestinal disorders           Myoch~ 3     FALSE   FALSE 
#> # ... with 116 more rows
```

<sup>Created on 2022-02-08 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

### PR DESCRIPTION
**Pull request by ddsjoberg**
**What changes are proposed in this pull request?**
- Added functions `modify_ae_header()` and `modify_ae_spanning_header()` to update the column headers and spanning headers of gtreg tables.
- Exporting new selectors to assist in selecting columns for updating headers and spanning headers
     - `all_ae_cols()` selects AE summary columns. By default, does not include the Unknown and Overall columns, and they can be included using the function's arguments
     - `all_strata_cols()` select columns based on the passed stratum level
     - `all_overall_cols()` select the overall columns
     - `all_unknown_cols()` select the unknown columns (i.e. when the by variable is NA)
- The tbl functions now include `.$header_info` tibble in the object that is used when the new headers include dynamic values like the by or stratum levels, and the N's within group.
- Previously, `add_overall()` removed the `.$inputs` object from the original tbl, and it is now retained and returned.
- Fixed bug when using `add_overall()` with `tbl_ae(id_df=)`
- Fixed bug in `tbl_ae_focus()` where the order of the columns was only correct for gt output.
- As users can now easily update the column headers, the `header_by=`, `header_strata=`, and `missing_text=` arguments have been removed.
- No longer returning complete_data object in tbl_ae functions
- Updating the argument order in all AE tbl functions
- Decided not to add argument `id=` and `id_df=` to `tbl_ae_count()`, and therefore, the Ns cannot be added to the strata headers for this table.

**If there is an GitHub issue associated with this pull request, please provide link.**
closes #87
closes #92
closes #89

--------------------------------------------------------------------------------

Checklist for PR reviewer

- [ ] Ensure all package dependencies are installed by running `renv::install()`
- [ ] PR branch has pulled the most recent updates from main branch. Ensure the pull request branch and your local version match and both have the latest updates from the main branch.
- [ ] If a new function was added, function included in `_pkgdown.yml`
- [ ] If a bug was fixed, a unit test was added for the bug check
- [ ] Run `pkgdown::build_site()`. Check the R console for errors, and review the rendered website.
- [ ] Code coverage is suitable for any new functions/features. Review coverage with `covr::report()`. Before you run, set `Sys.setenv(NOT_CRAN="true")` and begin in a fresh R session without any packages loaded. 
- [ ] R CMD Check runs without errors, warnings, and notes
- [ ] `usethis::use_spell_check()` runs with no spelling errors in documentation
- [ ] Has `NEWS.md` been updated with the changes from this pull request under the heading "`# gtreg (development version)`". If there is an issue associated with the pull request, reference it in parentheses at the end update (see `NEWS.md` for examples).
- [ ] Has the version number been incremented using `usethis::use_version(which = "dev")` 
- [ ] Approve Pull Request
- [ ] Merge the PR. Please use "Squash and merge".

### CODE REVIEW

**Comment by shannonpileggi** [comment]
Review in progress! Pushed a small update to utils.

**Comment by shannonpileggi** [comment]
What am I doing wrong here?  Is something not updated / installed appropriately on my end? 

Example from `test-tbl_ae.R`

image

``` r
devtools::session_info()
#> - Session info ---------------------------------------------------------------
#>  setting  value                       
#>  version  R version 4.1.1 (2021-08-10)
#>  os       Windows 10 x64              
#>  system   x86_64, mingw32             
#>  ui       RTerm                       
#>  language (EN)                        
#>  collate  English_United States.1252  
#>  ctype    English_United States.1252  
#>  tz       America/New_York            
#>  date     2022-02-13                  
#> 
#> - Packages -------------------------------------------------------------------
#>  package     * version date       lib source        
#>  brio          1.1.2   2021-04-23 [1] CRAN (R 4.1.1)
#>  cachem        1.0.6   2021-08-19 [1] CRAN (R 4.1.1)
#>  callr         3.7.0   2021-04-20 [1] CRAN (R 4.1.1)
#>  cli           3.1.1   2022-01-20 [1] CRAN (R 4.1.2)
#>  crayon        1.4.1   2021-02-08 [1] CRAN (R 4.1.1)
#>  desc          1.4.0   2021-09-28 [1] CRAN (R 4.1.1)
#>  devtools      2.4.2   2021-06-07 [1] CRAN (R 4.1.1)
#>  digest        0.6.28  2021-09-23 [1] CRAN (R 4.1.1)
#>  ellipsis      0.3.2   2021-04-29 [1] CRAN (R 4.1.1)
#>  evaluate      0.14    2019-05-28 [1] CRAN (R 4.1.1)
#>  fastmap       1.1.0   2021-01-25 [1] CRAN (R 4.1.1)
#>  fs            1.5.2   2021-12-08 [1] CRAN (R 4.1.2)
#>  glue          1.6.0   2021-12-17 [1] CRAN (R 4.1.2)
#>  highr         0.9     2021-04-16 [1] CRAN (R 4.1.1)
#>  htmltools     0.5.2   2021-08-25 [1] CRAN (R 4.1.1)
#>  knitr         1.37    2021-12-16 [1] CRAN (R 4.1.2)
#>  lifecycle     1.0.1   2021-09-24 [1] CRAN (R 4.1.1)
#>  magrittr      2.0.1   2020-11-17 [1] CRAN (R 4.1.1)
#>  memoise       2.0.0   2021-01-26 [1] CRAN (R 4.1.1)
#>  pkgbuild      1.2.0   2020-12-15 [1] CRAN (R 4.1.1)
#>  pkgload       1.2.3   2021-10-13 [1] CRAN (R 4.1.1)
#>  prettyunits   1.1.1   2020-01-24 [1] CRAN (R 4.1.1)
#>  processx      3.5.2   2021-04-30 [1] CRAN (R 4.1.1)
#>  ps            1.6.0   2021-02-28 [1] CRAN (R 4.1.1)
#>  purrr         0.3.4   2020-04-17 [1] CRAN (R 4.1.1)
#>  R6            2.5.1   2021-08-19 [1] CRAN (R 4.1.1)
#>  remotes       2.4.1   2021-09-29 [1] CRAN (R 4.1.1)
#>  reprex        2.0.1   2021-08-05 [1] CRAN (R 4.1.1)
#>  rlang         1.0.1   2022-02-03 [1] CRAN (R 4.1.2)
#>  rmarkdown     2.11    2021-09-14 [1] CRAN (R 4.1.1)
#>  rprojroot     2.0.2   2020-11-15 [1] CRAN (R 4.1.1)
#>  rstudioapi    0.13    2020-11-12 [1] CRAN (R 4.1.1)
#>  sessioninfo   1.1.1   2018-11-05 [1] CRAN (R 4.1.1)
#>  stringi       1.7.5   2021-10-04 [1] CRAN (R 4.1.1)
#>  stringr       1.4.0   2019-02-10 [1] CRAN (R 4.1.1)
#>  testthat      3.1.2   2022-01-20 [1] CRAN (R 4.1.2)
#>  usethis       2.1.2   2021-10-25 [1] CRAN (R 4.1.1)
#>  withr         2.4.3   2021-11-30 [1] CRAN (R 4.1.2)
#>  xfun          0.29    2021-12-14 [1] CRAN (R 4.1.2)
#>  yaml          2.2.1   2020-02-01 [1] CRAN (R 4.1.1)
#> 
#> [1] C:/Program Files/R/R-4.1.1/library
```

<sup>Created on 2022-02-13 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by shannonpileggi** [comment]
> What am I doing wrong here? Is something not updated / installed appropriately on my end?

OMG never mind. I ran `devtools::document()` and then built again.  We are good now.

**Comment by shannonpileggi** [comment]
Where should we expect the user to look for documentation regarding column selectors available?  Function examples, vignette?

**Comment by ddsjoberg** [comment]
> Where should we expect the user to look for documentation regarding column selectors available?  Function examples, vignette?

I was thinking we could add one of those Getting Started vignettes and include more complex examples there.(The selector help file also has examples) You are planning other vignettes too ( I think you mentioned that before). Would  we create a single vignette, or should they be separate?

**Comment by shannonpileggi** [comment]
What would you expect to be the output for these four scenarios? Should any warnings / errors be thrown for specific scenarios? 

```
library(gtreg)

t1 <- df_adverse_events %>%
  tbl_ae(
    id = patient_id,
    ae = adverse_event,
    statistic = "{n}"
  ) 

t1 %>% modify_ae_header(all_stat_cols() ~ "**Grade {by}**") 
t1 %>% modify_ae_header(all_ae_cols() ~ "**Grade {by}**") 
t1 %>% modify_ae_header(all_strata_cols() ~ "**Grade {by}**") 
t1 %>% modify_ae_header(all_unknown_cols() ~ "**Grade {by}**") 
```

(Full reprex w/ output not included b/c it is looking funny, no clue why.)

**Comment by shannonpileggi** [comment]
There are several `add_overall` tests in `tbl_ae` - should I move to `add_overall`?

**Comment by shannonpileggi** [comment]
Excuuuuseee me - I neglected to open with how awesome all of these updates are!!  So many big changes and great functionality!!

**Comment by shannonpileggi** [comment]
Should we have errors/messaging here? When overall/unknown = TRUE, that operates over other selector modifications.

```
library(gtreg)

tbl1 <-
  df_adverse_events %>%
  dplyr::mutate(grade = ifelse(dplyr::row_number() == 1L, NA, grade)) %>%
  tbl_ae(
    id = patient_id,
    id_df = df_patient_characteristics,
    ae = adverse_event,
    soc = system_organ_class,
    by = grade,
    strata = trt
  )

tbl2 <- add_overall(tbl1)

modify_ae_header(
  tbl2,
  all_overall_cols() ~ "**Total**",
  all_unknown_cols() ~ "**Unknown Grade**",
  all_ae_cols(overall = TRUE, unknown = TRUE) ~ "**Grade {by}**"
) 
```

**Comment by ddsjoberg** [comment]
> What would we expect to be the output for these four scenarios? Should any warnings / errors be thrown for specific scenarios?
> t1 %>% modify_ae_header(all_stat_cols() ~ "**Grade {by}**") 

The by level here is Overall, so we should see "Grade Overall"

> t1 %>% modify_ae_header(all_ae_cols() ~ "**Grade {by}**") 

I forgot to mark columns as overall from `tbl_ae()` as overall when by and strata and not specified. Just corrected. In this case, we're not selecting any Overall columns, so no change to the header.

> t1 %>% modify_ae_header(all_strata_cols() ~ "**Grade {by}**") 

This should error because there is no stratum and you can't select any stratum columns. We can try to work on improving the messaging....selectors are tricky, it'll take some thought.

> t1 %>% modify_ae_header(all_unknown_cols() ~ "**Grade {by}**")

since there are no Unknown cols, no change.

> Should a warning / message /error be thrown here? There is no overall column, but overall header modification specified.
> Should we have errors/messaging here? When overall/unknown = TRUE, that operates over other selector modifications.

The tidyselect/dplyr selectors don't error when you select nothing, and I like that behavior (particularly, when I am writing functions that use them). Same for the second comment!

**Review by shannonpileggi — APPROVED** [review]
BEAUTIFUL!

**Pull request merged**
