### PR TITLE
Updates to `add_overall()`

### LINKED ISSUE #42: `add_overall.tbl_adverse_event()` updates
- [ ] Allow for `add_overall()` to be run more than once on the same table (meaning cannot just use a `tbl_merge()` at the end). See @shannonpileggi suggestions here https://github.com/shannonpileggi/gtreg/pull/39#pullrequestreview-839614293
- [ ] Take more care with column placement in the `.$table_body` tibble. In the gt output, it'll group similar column headers and move columns, but the other formats do not do this.

### PR DESCRIPTION
**Pull request by ddsjoberg**
Hey @shannonpileggi ! Thanks for the great suggestions on `add_overall()`!

I think this version is much more user-friendly.

closes #42

### CODE REVIEW

**Comment by shannonpileggi** [comment]
This looks amazing!  I am going to document all possible combinations of `type`, `by`, and `strata` that I can think of.

# Starter table

```
df1 <-
  tibble::tibble(
    patient_id = paste0("ID", c(1,1,2,3)),
    system_organ_class = "organ",
    adverse_event = c("ae1", "ae1", "ae1", "ae2"),
    grade = c(1, 1, 1, 2),
    trt = rep("A", 4)
  )

id_valid <-
  tibble::tibble(
    patient_id = paste0("ID", 1:5),
    trt = c(rep("A", 3),rep("B", 2))
  )

x <- df1 %>%
  tbl_ae(
    id = patient_id,
    ae = adverse_event,
    soc = system_organ_class,
    by = grade,
    strata = trt,
    id_df = id_valid
  ) 

x
```

image

# 1 `by = FALSE`, `strata = FALSE`

### 1a `x %>% add_overall()`

image


### 1b `x %>% add_overall(type = "by")`

image


### 1c `x %>% add_overall(type = "strata")`

image


# 2 `by = TRUE, `strata = FALSE`

### 2a `x %>% add_overall(by = TRUE)`

image


### 2b `x %>% add_overall(type = "by", by = TRUE)`

image


### 2c `x %>% add_overall(type = "strata", by = TRUE)`

image


# 3 `by = FALSE`, `strata = TRUE`

### 3a `x %>% add_overall(strata = TRUE)`

image


### 3b `x %>% add_overall(type = "by", strata = TRUE)`

image


### 3c `x %>% add_overall(type = "strata", strata = TRUE)`

image


# 4 `by = TRUE`, `strata = TRUE`

### 4a `x %>% add_overall(by = TRUE, strata = TRUE)`

image


### 4b `x %>% add_overall(type = "by", by = TRUE, strata = TRUE)`

image


### 4c `x %>% add_overall(type = "strata", by = TRUE, strata = TRUE)`

image


# Summary

It looks like we have *12* possible combinations of parameters, resulting in *3* possible unique tables.

 + tables 1a, 2a, 3a, and 4a are identical - `type` option takes precedence over either `by` or `strata`

+ tables 1b, 2b, 3b, and 4b are identical

+ tables 1c 2c, 3c, and 4c are identical


I did this with copy/paste, nothing fancy, and a bunch of squinting, so if anything looks off please let me know!  

But if this is the case and we only have 3 unique tables, then does a single `type` argument suffice?  What am I am missing? I am tired and if I have missed something pls let me know!

Lastly, I think there was an option in the previous iteration that is no longer available (a table on my deliverable list) where there is a single overall column added to the initial output:

image

Could a single overall, across everything, column be incorporated?

**Review by shannonpileggi — COMMENTED** [review]
Not sure if the comment I submitted went through as part of the review or not.

**Comment by ddsjoberg** [comment]
@shannonpileggi thank you for the review!

The `add_overall(by=, strata=)` arguments were replaced with `add_overall(type=)`, which only has three options. When `by=, strata=` were passed they were swallowed by the `...` argument and ignored. In the next version of rlang (coming very soon, I think), there is a new function `rlang::check_dots_empty()` that we can add to ensure erroneous arguments don't get mistakenly ignored.

Here is the original table

image

```r
add_overall(type = "both")
```

image


```r
add_overall(type = "by")
```

image


```r
add_overall(type = "strata")
```

image


> Could a single overall, across everything, column be incorporated?

image

You can get this table by hiding the extra columns from `add_overall(type = "both")`. We can also add a fourth option. What do you think it should be called?

**Comment by shannonpileggi** [comment]
🤦 I knew I was missing something!  Sorry!

The hide columns approach when `type = "both"` works, and would be great to add to documentation somewhere. I'm happy to tackle that.

A fourth option would also be nice, but I am struggling with the name.  Here are some ideas that I don't love:

- `type = "margin"`
- `type = "marginal"`
- `type = "total"`

**Comment by ddsjoberg** [comment]
> 🤦 I knew I was missing something! Sorry!

It was my bad! I removed the arguments from the function, but left in the roxygen2 comment documenting them 😖

**Review by shannonpileggi — APPROVED** [review]
What an accomplishment!!  

I committed to the tests file on this PR, removed some of the older examples using older arguments.

Woohoo!

**Pull request merged**
