### PR TITLE
Adding N to strata header

### LINKED ISSUE #41: `tbl_adverse_event()` add n to table header
```
df1 <-
  tibble::tibble(
    patient_id = paste0("ID", c(1,1,2,3)),
    system_organ_class = "Blood and lymphatic system disorders",
    adverse_event = c("Anaemia", "Anaemia", "Anaemia", "Increased tendency to bruise"),
    grade = c(1, 1, 1, 2),
    trt = rep("A", 4)
  )

id_valid <-
  tibble::tibble(
    patient_id = paste0("ID", 1:5),
    trt = c(rep("A", 3),rep("B", 2))
  )

  tbl_adverse_event(
    data = df1,
    id = "patient_id",
    ae = "adverse_event",
    soc = "system_organ_class",
    by = "grade",
    strata = "trt",
    id_df = id_valid,
    by_values = as.character(c(1:5))
  )

```

currently yields

image

What do you think about updating the default output to include `N = x`, similar to `gtsummary::tbl_summary()`?

### PR DESCRIPTION
**Pull request by ddsjoberg**
closes #41

### CODE REVIEW

**Comment by ddsjoberg** [comment]
@shannonpileggi i think this one is ready for review. I like the default headers everywhere, but suspect you'll not like the (no) header for `add_overall(across = overall-only)` 😄

**Comment by shannonpileggi** [comment]
thanks for these amazing updates!  i'm so excited about this!  i committed some additional tests to `test-tbl_ae()`. three are left commented out that might be edge cases to address - let me know what you think.  i'll put each one in a separate comment here.

**Comment by shannonpileggi** [comment]
a user may incorrectly attempt a `header_by` without a `by`, or a `header_strata` with a `by`

```
    df_adverse_events %>%
       tbl_ae(
         id = patient_id,
         ae = adverse_event,
         statistic = "{n}",
         header_by = "**Grade {level}**"
       )
```

```
  df_adverse_events %>%
      tbl_ae(
        id = patient_id,
        ae = adverse_event,
        statistic = "{n}",
        by = grade,
        header_strata = "**Cohort {level}**"
      )
```

these do not currently return a warning or message - should it?

**Comment by shannonpileggi** [comment]
i think when `header_by` is specified without `by`

the table inserts headers.  what should be the expected behavior here?


```
 df_adverse_events %>%
      tbl_ae(
        id = patient_id,
        ae = adverse_event,
        statistic = "{n}",
        strata = trt,
        header_by = "**Cohort {level}**"
      )
```

image

here is what the table looks like without the `header_by`

```
 df_adverse_events %>%
      tbl_ae(
        id = patient_id,
        ae = adverse_event,
        statistic = "{n}",
        strata = trt
      )
```

image

**Comment by ddsjoberg** [comment]
> a user may incorrectly attempt a `header_by` without a `by`
> and a user may incorrectly specify a `header_strata` with a `by`.
> these do not currently return a warning or message - should it?

I think there are multiple ways to handle this:
1. Make it clear in the documentation these are meant to be used with the `by=` and `strata=` args. I like this because we can leave the default value in the function call, which gives a hint to the users how to implement the glue syntax header changes.
2.  We could make the default value `NULL`, and when either `by=` or `strata=` are specified we set the default value internally if not specified, e.g. `header_by <- header_by  %||% "{level}"`.

Either of these is fine with me! What is your preference? I lean towards the first, which needs a documentation update.

**Comment by ddsjoberg** [comment]
> i think when `header_by` is specified without `by` the table inserts headers.  what should be the expected behavior here?

Hmmm good point. I am not sure what the default should be. Even when no by variable is present in the function call, we do indeed utilize a by variable in the background (adding levels for Unobserved or Missing). This is why the `header_by=` value has an affect on the headers even with no `by=` passed.

I am fine with whatever solution you prefer, by that leaving it as is, or ignoring any passed value in `header_by=` when `by=` is not specified.

**Comment by ddsjoberg** [comment]
I'll update to require that by and specified when specifying header_by

**Review by shannonpileggi — CHANGES_REQUESTED** [review]
You are so speedy!!  

I pushed a couple of updates to the test file.  

One is still failing that I can't quite figure out - are these supposed to be errors, messages, or warnings? What am I missing?

**Comment by ddsjoberg** [comment]
> One is still failing that I can't quite figure out - are these supposed to be errors, messages, or warnings? What am I missing?

I made it so the return errors when the headers are specified. I pushed updates to the tests.

**Comment by shannonpileggi** [comment]
Ok thank you!! Not sure what is up with the windows check, but otherwise looks good to me!

**Pull request merged**
